# Generated by Django 5.1.3 on 2024-12-13 13:53

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('service_type', models.CharField(max_length=50, verbose_name='Тип услуги')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
    ]